### ISSUE TITLE
Need to update the Podfile

### ISSUE THREAD

**Issue by eliassun** [ringcentral/ringcentral-swift#14]
When I compiled the SDK, it failed. It needs to update Podfile to make the current swift-2 branch to pass the compilation.

1. There is some bad characters in Podfile, which need to be removed. 
2. Podfile: Also, it needs to update the "SwiftyJSON" branch to swift21 
3. Podfile: Also, it needs to update "CryptoSwift" to the branch swift2

Now, the SDK can be compiled.

**Comment by anilkumarbp** [comment]
The reason why the command `pod install` fails is because the dependencies have a different version which support  Swift 2.0

Updating the below dependencies to the respective branch : 
- `SwiftyJSON`  ->  `swift21`  ( https://github.com/SwiftyJSON/SwiftyJSON/tree/swift2 )
- `CryptoSwift`  ->  `master`   ( reverted to `master` branch as it supports Swift 2.0 now )
